appId: com.icesjs.viper
copyright: Copyright © 2020 Icesjs️
productName: Viper
publish: false
dmg:
  sign: false
  icon: assets/icon.dmg.icns
  contents:
    - type: link
      path: /Applications
      x: 410
      'y': 150
    - type: file
      x: 130
      'y': 150
mac:
  target: dmg
  category: public.app-category.entertainment
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  hardenedRuntime: true
  gatekeeperAssess: false
  darkModeSupport: false
  electronLanguages:
    - en_US
    - zh_CN
  icon: assets/icon.icns
win:
  target: nsis
  icon: assets/icon.ico
linux:
  target:
    - deb
    - AppImage
  category: Entertainment
  icon: assets/icon.png
asar: true
extends: null
directories:
  buildResources: build/
  output: dist/
  app: build/
files:
  - '!*.{js,css}.map'
  - package.json
  - main/index.js
  - main/**/*
  - renderer/**/*
  - addons/**/*
extraMetadata:
  main: main/index.js
