appId: com.icesjs.viper
copyright: Copyright © 2020 Icesjs️
productName: Viper
dmg:
  sign: false
  icon: public/app/icon.dmg.icns
  contents:
    - type: link
      path: /Applications
      x: 410
      'y': 150
    - type: file
      x: 130
      'y': 150
mac:
  target: dmg
  category: public.app-category.entertainment
  entitlements: public/app/entitlements.mac.plist
  entitlementsInherit: public/app/entitlements.mac.plist
  hardenedRuntime: true
  gatekeeperAssess: false
  darkModeSupport: false
  electronLanguages:
    - en_US
    - zh_CN
  icon: public/app/icon.icns
  publish:
    - github
win:
  target: nsis
  icon: public/app/icon.ico
  publish:
    - github
linux:
  target:
    - deb
    - AppImage
  category: Entertainment
  icon: public/app/icon.png
  publish:
    - github
asar: true
extends: null
npmRebuild: false
publish: never
electronVersion: 11.1.1
directories:
  buildResources: build/
  output: dist/
  app: build/
files:
  - '!*.{js,css}.map'
  - package.json
  - main/index.js
  - main/**/*
  - renderer/**/*
  - addons/**/*
extraMetadata:
  main: main/index.js
