# used for electron-builder
appId: com.icesjs.viper
copyright: Copyright © 2020 Icesjs️
productName: Viper

asar: false
npmRebuild: true
extends: null

publish: null

directories:
  buildResources: assets/
  output: dist/
  app: build/

files:
  - build/**/*
  - '!*.{ js,css }.map'

extraResources:
  - assets/**/*

extraMetadata:
  main: index.js

dmg:
  sign: false
  icon: assets/icon.dmg.icns
  contents:
    - type: link
      path: /Applications
      x: 410
      y: 150
    - type: file
      x: 130
      y: 150

mac:
  target: dmg
  category: public.app-category.entertainment
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  hardenedRuntime: true
  gatekeeperAssess: false
  icon: assets/icon.icns

win:
  target: nsis
  icon: assets/icon.ico

linux:
  target:
    - deb
    - AppImage
  category: Entertainment
  icon: assets/icon.png
